### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Odonno** [Odonno/FeatureManagement.UI#4]
Here is the roadmap with a list of all possible features to add in the next releases:

* Native Feature **value** types
  * [x] boolean
  * [x] integer
  * [x] decimal
  * [x] string
  * [x] List of choices
* Extended feature value types
  * [ ] Color
    * [ ] Color Picker on the UI
    * [ ] With validation
    * [ ] Custom display
  * [ ] Date
    * [ ] Timestamp on the UI
    * [ ] With validation
    * [ ] Custom display
  * [ ] Json
    * [ ] Textarea on the UI
    * [ ] With validation
    * [ ] Auto format 
  * [x] Prefix/suffix (only for UI)
* Feature definitions
  * [x] Static configuration (current) = `ResetOnStartup`
  * [ ] Improved Configuration Builder (better readability, maintainability & type checking)
  * [ ] Load from `appsettings.json`
  * [ ] Dynamic configuration (with `CreateFeature`, `UpdateFeature` and `RemoveFeature`)
* Storage Providers (via EF Core)
  * [x] In memory
  * [x] SQL Server
  * [ ] PostgreSQL
  * [ ] MySQL
  * [ ] SQLite
  * [ ] Custom Storage Provider?
* Feature types
  * [x] Global feature configuration (default as `ServerFeature`) `manual changes allowed`
  * [x] Client feature configuration (default as `ClientFeature`) `manual changes allowed`
  * [x] Time window feature configuration (after date, before date, between dates) `requires HostedService`
  * [x] Group feature configuration
  * [ ] Client rollout feature configuration (% of clients - with Slider UI) `requires HostedService`
  * [ ] Group rollout feature configuration (% of groups - with Slider UI) `requires HostedService`
  * [ ] Custom feature configuration?
* User Interface
  * [x] Display list of features (with the best component for the job)
  * [ ] Add details on each feature (icon for feature type, tags : client vs. server / rollout / group / time window)
  * [ ] Button to display/hide disabled features
  * [ ] Search features
  * [ ] Group features (display features on categories)
  * [ ] Allow HTML customization
  * [ ] Allow CSS customization
  * [ ] Pass down props from url (ex: authentication scheme & value)
* Authentication
  * [x] Allow/Disallow `read` right
  * [x] Allow/Disallow `write` right
  * [x] `readonly` property to disable UI components
  * [x] Authentication schemes like Query params or Headers (API usage + UI selection)
* Realtime updates
  * [x] Feature updated event handlers (both server and client features)
  * [ ] API (websocket) realtime events
  * [ ] Automatically update the UI using realtime events
* Documentation
  * [x] Basic documentation (goals, code documentation/usage, images)
  * [x] Split documentation by feature/domain (like here)
* Improvements ideas
  * [ ] Caching
  * [ ] GraphQL API to replace the REST API (real-time subscription for free)
